from __future__ import annotations

import hashlib
from typing import Any


def _variant(prompt: str, answer_spec: dict[str, Any]) -> dict[str, Any]:
    return {"prompt": prompt, "answer_spec": answer_spec}


def _choice_variant(question: str, answer_spec: dict[str, Any], *, template: str) -> dict[str, Any]:
    return {
        "variant_kind": "choice_template",
        "question": question,
        "template": template,
        "answer_spec": answer_spec,
    }


def _ordered_variant(question: str, answer_spec: dict[str, Any], *, template: str) -> dict[str, Any]:
    return {
        "variant_kind": "ordered_template",
        "question": question,
        "template": template,
        "answer_spec": answer_spec,
    }


def _text(*accepted: str) -> dict[str, Any]:
    return {"type": "text", "accepted": [item for item in accepted if str(item).strip()]}


def _numeric(value: int | float) -> dict[str, Any]:
    return {"type": "numeric", "value": value}


def _boolean(value: bool) -> dict[str, Any]:
    return {"type": "boolean", "value": value}


def _choice(*choices: str, answer: str) -> dict[str, Any]:
    return {"type": "multiple_choice", "choices": list(choices), "answer": answer}


def _ordered(*tokens: str) -> dict[str, Any]:
    return {"type": "ordered_tokens", "tokens": list(tokens)}


def _seed(
    concept_id: str,
    category: str,
    difficulty: int,
    family_id: str,
    *,
    tags: tuple[str, ...],
    variants: tuple[dict[str, Any], ...],
) -> dict[str, Any]:
    return {
        "concept_id": concept_id,
        "family_id": family_id,
        "category": category,
        "difficulty": difficulty,
        "source_type": "curated",
        "generator_type": "static_pack",
        "variants": variants,
        "tags": tags,
        "attribution": None,
    }


def _pick_templates(concept_id: str, templates: tuple[str, ...], *, count: int = 5) -> tuple[str, ...]:
    if count >= len(templates):
        return templates[:count]
    digest = int(hashlib.sha256(concept_id.encode("utf-8")).hexdigest()[:8], 16)
    start = digest % len(templates)
    return tuple(templates[(start + index) % len(templates)] for index in range(count))


SCIENCE_TEXT_TEMPLATES = (
    "{clue}",
    "Quick science clue: {clue}",
    "Science snap: {clue}",
    "Name the science answer that fits this clue: {clue}",
    "Babblebox science round: {clue}",
    "Compact lab clue: {clue}",
    "Which science answer fits best here? {clue}",
    "Short science prompt: {clue}",
)
SCIENCE_CHOICE_TEMPLATES = (
    "{question} A) {a} B) {b} C) {c}",
    "Quick pick: {question} A) {a} B) {b} C) {c}",
    "Science multiple-choice: {question} A) {a} B) {b} C) {c}",
    "Lock in the best science answer. {question} A) {a} B) {b} C) {c}",
    "Which option fits this science clue? {question} A) {a} B) {b} C) {c}",
    "Science lane: {question} A) {a} B) {b} C) {c}",
    "Choose the cleanest science answer. {question} A) {a} B) {b} C) {c}",
    "Compact science MC: {question} A) {a} B) {b} C) {c}",
)
SCIENCE_BOOLEAN_TEMPLATES = (
    "True or false: {statement}",
    "Science check, true or false: {statement}",
    "Call this science statement true or false: {statement}",
    "Quick T/F: {statement}",
    "Science lane T/F: {statement}",
    "Decide whether this science claim is true or false: {statement}",
    "Truth test: {statement}",
    "Science statement: {statement}. True or false?",
)
SCIENCE_NUMERIC_TEMPLATES = (
    "{question}",
    "Science quick number: {question}",
    "Numeric science clue: {question}",
    "Science lane asks: {question}",
    "Short science number round: {question}",
    "Lock in the number: {question}",
    "Compact science prompt: {question}",
    "Science card: {question}",
)

HISTORY_TEXT_TEMPLATES = (
    "{clue}",
    "History clue: {clue}",
    "Quick history round: {clue}",
    "Name the history answer that fits this clue: {clue}",
    "Babblebox history prompt: {clue}",
    "Compact timeline clue: {clue}",
    "Which history answer belongs here? {clue}",
    "Short history card: {clue}",
)
HISTORY_CHOICE_TEMPLATES = (
    "{question} A) {a} B) {b} C) {c}",
    "History pick: {question} A) {a} B) {b} C) {c}",
    "Choose the best history answer. {question} A) {a} B) {b} C) {c}",
    "Timeline check: {question} A) {a} B) {b} C) {c}",
    "History multiple-choice: {question} A) {a} B) {b} C) {c}",
    "Compact history MC: {question} A) {a} B) {b} C) {c}",
    "Lock in the history answer. {question} A) {a} B) {b} C) {c}",
    "Which history option fits? {question} A) {a} B) {b} C) {c}",
)
HISTORY_ORDERED_TEMPLATES = (
    "{question}: {items}",
    "History order round. {question}: {items}",
    "Put this timeline in order. {question}: {items}",
    "Chronology check. {question}: {items}",
    "Babblebox history ordering. {question}: {items}",
    "Order these cleanly. {question}: {items}",
    "History lane asks for sequence. {question}: {items}",
    "Arrange the timeline. {question}: {items}",
)

GEOGRAPHY_TEXT_TEMPLATES = (
    "{clue}",
    "Geography clue: {clue}",
    "Quick mapless clue: {clue}",
    "Name the place or feature that fits: {clue}",
    "Babblebox geography prompt: {clue}",
    "Compact geography clue: {clue}",
    "Which geography answer belongs here? {clue}",
    "Short geography card: {clue}",
)
GEOGRAPHY_CHOICE_TEMPLATES = (
    "{question} A) {a} B) {b} C) {c}",
    "Geography pick: {question} A) {a} B) {b} C) {c}",
    "Choose the strongest geography answer. {question} A) {a} B) {b} C) {c}",
    "Mapless multiple-choice: {question} A) {a} B) {b} C) {c}",
    "Geography lane: {question} A) {a} B) {b} C) {c}",
    "Compact geography MC: {question} A) {a} B) {b} C) {c}",
    "Lock in the geography answer. {question} A) {a} B) {b} C) {c}",
    "Which geography option fits? {question} A) {a} B) {b} C) {c}",
)
GEOGRAPHY_ORDERED_TEMPLATES = (
    "{question}: {items}",
    "Geography order round. {question}: {items}",
    "Arrange these geographically. {question}: {items}",
    "Latitude or sequence check. {question}: {items}",
    "Babblebox geography ordering. {question}: {items}",
    "Order these places cleanly. {question}: {items}",
    "Geography lane asks for sequence. {question}: {items}",
    "Put this geography list in order. {question}: {items}",
)

LANGUAGE_TEXT_TEMPLATES = (
    "{clue}",
    "Language clue: {clue}",
    "Quick wordplay clue: {clue}",
    "Name the language answer that fits: {clue}",
    "Babblebox language prompt: {clue}",
    "Compact language clue: {clue}",
    "Which language answer belongs here? {clue}",
    "Short language card: {clue}",
)
LANGUAGE_CHOICE_TEMPLATES = (
    "{question} A) {a} B) {b} C) {c}",
    "Language pick: {question} A) {a} B) {b} C) {c}",
    "Choose the cleanest language answer. {question} A) {a} B) {b} C) {c}",
    "Wordplay multiple-choice: {question} A) {a} B) {b} C) {c}",
    "Language lane: {question} A) {a} B) {b} C) {c}",
    "Compact language MC: {question} A) {a} B) {b} C) {c}",
    "Lock in the language answer. {question} A) {a} B) {b} C) {c}",
    "Which language option fits? {question} A) {a} B) {b} C) {c}",
)
LANGUAGE_BOOLEAN_TEMPLATES = (
    "True or false: {statement}",
    "Grammar check, true or false: {statement}",
    "Language lane T/F: {statement}",
    "Call this usage statement true or false: {statement}",
    "Quick language T/F: {statement}",
    "Decide whether this language claim is true or false: {statement}",
    "Truth test: {statement}",
    "Language statement: {statement}. True or false?",
)
LANGUAGE_ORDERED_TEMPLATES = (
    "{question}: {items}",
    "Language order round. {question}: {items}",
    "Put this word blend in order. {question}: {items}",
    "Sequence check. {question}: {items}",
    "Babblebox language ordering. {question}: {items}",
    "Order the terms cleanly. {question}: {items}",
    "Language lane asks for sequence. {question}: {items}",
    "Arrange these in order. {question}: {items}",
)

CULTURE_TEXT_TEMPLATES = (
    "{clue}",
    "Culture clue: {clue}",
    "Quick culture card: {clue}",
    "Name the culture answer that fits: {clue}",
    "Babblebox culture prompt: {clue}",
    "Compact culture clue: {clue}",
    "Which culture answer belongs here? {clue}",
    "Short culture round: {clue}",
)
CULTURE_CHOICE_TEMPLATES = (
    "{question} A) {a} B) {b} C) {c}",
    "Culture pick: {question} A) {a} B) {b} C) {c}",
    "Choose the best culture answer. {question} A) {a} B) {b} C) {c}",
    "Culture multiple-choice: {question} A) {a} B) {b} C) {c}",
    "Babblebox culture lane: {question} A) {a} B) {b} C) {c}",
    "Compact culture MC: {question} A) {a} B) {b} C) {c}",
    "Lock in the culture answer. {question} A) {a} B) {b} C) {c}",
    "Which culture option fits? {question} A) {a} B) {b} C) {c}",
)
CULTURE_ORDERED_TEMPLATES = (
    "{question}: {items}",
    "Culture order round. {question}: {items}",
    "Arrange these culture terms in order. {question}: {items}",
    "Sequence check. {question}: {items}",
    "Babblebox culture ordering. {question}: {items}",
    "Order the list cleanly. {question}: {items}",
    "Culture lane asks for sequence. {question}: {items}",
    "Put this list in order. {question}: {items}",
)
CULTURE_NUMERIC_TEMPLATES = (
    "{question}",
    "Culture quick number: {question}",
    "Numeric culture clue: {question}",
    "Culture lane asks: {question}",
    "Short culture number round: {question}",
    "Lock in the number: {question}",
    "Compact culture prompt: {question}",
    "Culture card: {question}",
)

LOGIC_TEXT_TEMPLATES = (
    "{clue}",
    "Logic clue: {clue}",
    "Reason it out: {clue}",
    "Compact logic puzzle: {clue}",
    "Babblebox logic prompt: {clue}",
    "Short deduction card: {clue}",
    "Which answer fits the logic here? {clue}",
    "Logic lane asks: {clue}",
)
LOGIC_CHOICE_TEMPLATES = (
    "{question} A) {a} B) {b} C) {c}",
    "Logic pick: {question} A) {a} B) {b} C) {c}",
    "Choose the strongest deduction. {question} A) {a} B) {b} C) {c}",
    "Compact logic MC: {question} A) {a} B) {b} C) {c}",
    "Reasoning multiple-choice: {question} A) {a} B) {b} C) {c}",
    "Babblebox logic lane: {question} A) {a} B) {b} C) {c}",
    "Lock in the logic answer. {question} A) {a} B) {b} C) {c}",
    "Which logical option fits? {question} A) {a} B) {b} C) {c}",
)
LOGIC_BOOLEAN_TEMPLATES = (
    "True or false: {statement}",
    "Logic check, true or false: {statement}",
    "Reasoning T/F: {statement}",
    "Call this deduction true or false: {statement}",
    "Quick logic T/F: {statement}",
    "Decide whether this conclusion follows: {statement}",
    "Truth test: {statement}",
    "Logic statement: {statement}. True or false?",
)
LOGIC_ORDERED_TEMPLATES = (
    "{question}: {items}",
    "Logic order round. {question}: {items}",
    "Arrange the clues in order. {question}: {items}",
    "Sequence deduction. {question}: {items}",
    "Babblebox logic ordering. {question}: {items}",
    "Order this logic list cleanly. {question}: {items}",
    "Logic lane asks for sequence. {question}: {items}",
    "Put the items in order. {question}: {items}",
)
LOGIC_NUMERIC_TEMPLATES = (
    "{question}",
    "Logic quick number: {question}",
    "Numeric deduction: {question}",
    "Babblebox logic asks: {question}",
    "Short logic number round: {question}",
    "Lock in the number: {question}",
    "Compact logic prompt: {question}",
    "Reasoning card: {question}",
)

MATH_TEXT_TEMPLATES = (
    "{clue}",
    "Math sense clue: {clue}",
    "Mental-math prompt: {clue}",
    "Number sense round: {clue}",
    "Babblebox math prompt: {clue}",
    "Compact math clue: {clue}",
    "Which math answer fits here? {clue}",
    "Short math card: {clue}",
)
MATH_CHOICE_TEMPLATES = (
    "{question} A) {a} B) {b} C) {c}",
    "Math pick: {question} A) {a} B) {b} C) {c}",
    "Choose the strongest number-sense answer. {question} A) {a} B) {b} C) {c}",
    "Mental-math multiple-choice: {question} A) {a} B) {b} C) {c}",
    "Babblebox math lane: {question} A) {a} B) {b} C) {c}",
    "Compact math MC: {question} A) {a} B) {b} C) {c}",
    "Lock in the math answer. {question} A) {a} B) {b} C) {c}",
    "Which math option fits? {question} A) {a} B) {b} C) {c}",
)
MATH_NUMERIC_TEMPLATES = (
    "{question}",
    "Mental math: {question}",
    "Number-sense quick hit: {question}",
    "Babblebox math asks: {question}",
    "Short math number round: {question}",
    "Lock in the number: {question}",
    "Compact math prompt: {question}",
    "Math card: {question}",
)


def _text_seed(
    concept_id: str,
    category: str,
    difficulty: int,
    family_id: str,
    *,
    subcategory: str,
    mode: str,
    accepted: tuple[str, ...],
    clue: str,
    templates: tuple[str, ...],
) -> dict[str, Any]:
    return _seed(
        concept_id,
        category,
        difficulty,
        family_id,
        tags=(f"sub:{subcategory}", f"mode:{mode}", "shape:text"),
        variants=tuple(_variant(template.format(clue=clue), _text(*accepted)) for template in _pick_templates(concept_id, templates)),
    )


def _choice_seed(
    concept_id: str,
    category: str,
    difficulty: int,
    family_id: str,
    *,
    subcategory: str,
    mode: str,
    question: str,
    options: tuple[str, str, str],
    answer: str,
    templates: tuple[str, ...],
    extra_tags: tuple[str, ...] = (),
) -> dict[str, Any]:
    return _seed(
        concept_id,
        category,
        difficulty,
        family_id,
        tags=tuple(extra_tags) + (f"sub:{subcategory}", f"mode:{mode}", "shape:multiple_choice"),
        variants=tuple(
            _choice_variant(
                question,
                _choice(*options, answer=answer),
                template=template,
            )
            for template in _pick_templates(concept_id, templates)
        ),
    )


def _boolean_seed(
    concept_id: str,
    category: str,
    difficulty: int,
    family_id: str,
    *,
    subcategory: str,
    mode: str,
    statement: str,
    value: bool,
    templates: tuple[str, ...],
    extra_tags: tuple[str, ...] = (),
) -> dict[str, Any]:
    return _seed(
        concept_id,
        category,
        difficulty,
        family_id,
        tags=tuple(extra_tags) + (f"sub:{subcategory}", f"mode:{mode}", "shape:boolean"),
        variants=tuple(_variant(template.format(statement=statement), _boolean(value)) for template in _pick_templates(concept_id, templates)),
    )


def _ordered_seed(
    concept_id: str,
    category: str,
    difficulty: int,
    family_id: str,
    *,
    subcategory: str,
    mode: str,
    question: str,
    tokens: tuple[str, ...],
    templates: tuple[str, ...],
) -> dict[str, Any]:
    return _seed(
        concept_id,
        category,
        difficulty,
        family_id,
        tags=(f"sub:{subcategory}", f"mode:{mode}", "shape:ordered_tokens"),
        variants=tuple(
            _ordered_variant(
                question,
                _ordered(*tokens),
                template=template,
            )
            for template in _pick_templates(concept_id, templates)
        ),
    )


def _numeric_seed(
    concept_id: str,
    category: str,
    difficulty: int,
    family_id: str,
    *,
    subcategory: str,
    mode: str,
    question: str,
    value: int | float,
    templates: tuple[str, ...],
) -> dict[str, Any]:
    return _seed(
        concept_id,
        category,
        difficulty,
        family_id,
        tags=(f"sub:{subcategory}", f"mode:{mode}", "shape:numeric"),
        variants=tuple(_variant(template.format(question=question), _numeric(value)) for template in _pick_templates(concept_id, templates)),
    )


EXPANDED_STATIC_SEEDS: tuple[dict[str, Any], ...] = (
    _text_seed(
        "science:aurora-atmosphere",
        "science",
        2,
        "science.space-weather-aurora",
        subcategory="space-weather",
        mode="causal",
        accepted=("atmosphere", "the atmosphere"),
        clue="The northern lights happen when charged particles collide with gases in which layer around Earth?",
        templates=SCIENCE_TEXT_TEMPLATES,
    ),
    _choice_seed(
        "science:tectonic-collision-mountains",
        "science",
        2,
        "science.tectonics-collision",
        subcategory="tectonics",
        mode="classification",
        question="Which process builds major folded mountain chains like the Himalayas?",
        options=("two tectonic plates colliding", "daily ocean tides", "wind erosion alone"),
        answer="two tectonic plates colliding",
        templates=SCIENCE_CHOICE_TEMPLATES,
    ),
    _text_seed(
        "science:solar-eclipse-position",
        "science",
        1,
        "science.earth-sun-moon-alignment",
        subcategory="astronomy",
        mode="spatial",
        accepted=("moon", "the moon"),
        clue="A total solar eclipse happens when which object moves between Earth and the Sun?",
        templates=SCIENCE_TEXT_TEMPLATES,
    ),
    _text_seed(
        "science:enzyme-catalyst",
        "science",
        2,
        "science.biology-enzymes",
        subcategory="biology",
        mode="function",
        accepted=("catalyst", "catalysts"),
        clue="In biology, enzymes mainly speed up reactions by acting as what?",
        templates=SCIENCE_TEXT_TEMPLATES,
    ),
    _choice_seed(
        "science:keystone-species",
        "science",
        3,
        "science.ecology-keystone",
        subcategory="ecology",
        mode="classification",
        question="A species whose removal dramatically reshapes an ecosystem is called what?",
        options=("keystone species", "pioneer species", "indicator mineral"),
        answer="keystone species",
        templates=SCIENCE_CHOICE_TEMPLATES,
    ),
    _text_seed(
        "science:vaccine-immune-memory",
        "science",
        2,
        "science.immunology-memory",
        subcategory="immunology",
        mode="causal",
        accepted=("immune system", "the immune system"),
        clue="Vaccines train which system to recognize a future infection faster?",
        templates=SCIENCE_TEXT_TEMPLATES,
    ),
    _boolean_seed(
        "science:ice-density",
        "science",
        2,
        "science.matter-density",
        subcategory="matter",
        mode="principle",
        statement="Ice floats because solid water is less dense than liquid water.",
        value=True,
        templates=SCIENCE_BOOLEAN_TEMPLATES,
    ),
    _boolean_seed(
        "science:sound-vacuum",
        "science",
        2,
        "science.sound-medium",
        subcategory="waves",
        mode="principle",
        statement="Sound can travel through empty vacuum the same way it moves through air.",
        value=False,
        templates=SCIENCE_BOOLEAN_TEMPLATES,
    ),
    _text_seed(
        "science:seatbelt-inertia",
        "science",
        2,
        "science.motion-inertia",
        subcategory="physics",
        mode="causal",
        accepted=("inertia",),
        clue="Seat belts help in sudden stops because your body resists changes in motion due to what?",
        templates=SCIENCE_TEXT_TEMPLATES,
    ),
    _numeric_seed(
        "science:neutral-ph",
        "science",
        1,
        "science.chemistry-ph",
        subcategory="chemistry",
        mode="fact",
        question="On the pH scale, which whole number is neutral?",
        value=7,
        templates=SCIENCE_NUMERIC_TEMPLATES,
    ),
    _choice_seed(
        "science:fossil-sedimentary",
        "science",
        2,
        "science.earth-science-fossils",
        subcategory="earth-science",
        mode="classification",
        question="Most fossils are found in which type of rock?",
        options=("sedimentary", "igneous", "metamorphic"),
        answer="sedimentary",
        templates=SCIENCE_CHOICE_TEMPLATES,
    ),
    _text_seed(
        "science:control-variables",
        "science",
        3,
        "science.experimental-controls",
        subcategory="experimental-design",
        mode="method",
        accepted=("control variables", "controlled variables", "controls"),
        clue="If an experiment changes fertilizer but keeps pot size, water, and light the same, those unchanged factors are the what?",
        templates=SCIENCE_TEXT_TEMPLATES,
    ),
    _text_seed(
        "science:adaptation-definition",
        "science",
        2,
        "science.evolution-adaptation",
        subcategory="evolution",
        mode="definition",
        accepted=("adaptation", "an adaptation"),
        clue="A trait that helps an organism survive and reproduce in its environment is called an what?",
        templates=SCIENCE_TEXT_TEMPLATES,
    ),
    _choice_seed(
        "science:radiocarbon-carbon-14",
        "science",
        3,
        "science.radiocarbon-dating",
        subcategory="chemistry",
        mode="classification",
        question="Radiocarbon dating measures the decay of which isotope?",
        options=("carbon-14", "carbon-12", "oxygen-18"),
        answer="carbon-14",
        templates=SCIENCE_CHOICE_TEMPLATES,
    ),
    _text_seed(
        "science:transform-boundary-san-andreas",
        "science",
        3,
        "science.plate-tectonics-transform",
        subcategory="tectonics",
        mode="classification",
        accepted=("transform boundary", "a transform boundary", "transform fault"),
        clue="The San Andreas Fault is the classic example of what kind of plate boundary, where plates slide past one another?",
        templates=SCIENCE_TEXT_TEMPLATES,
    ),
    _text_seed(
        "science:coral-bleaching-algae",
        "science",
        3,
        "science.coral-bleaching",
        subcategory="ecology",
        mode="causal",
        accepted=("algae", "zooxanthellae", "symbiotic algae"),
        clue="When corals bleach, they have usually lost which symbiotic organisms that help feed them?",
        templates=SCIENCE_TEXT_TEMPLATES,
    ),
    _boolean_seed(
        "science:venus-day-year",
        "science",
        3,
        "science.planetary-rotation-venus",
        subcategory="astronomy",
        mode="comparison",
        statement="On Venus, one full rotation takes longer than one trip around the Sun.",
        value=True,
        templates=SCIENCE_BOOLEAN_TEMPLATES,
    ),
    _text_seed(
        "history:rosetta-hieroglyphs",
        "history",
        3,
        "history.decoding-hieroglyphs",
        subcategory="ancient-world",
        mode="context",
        accepted=("hieroglyphs", "egyptian hieroglyphs", "hieroglyphics"),
        clue="The Rosetta Stone became famous because it helped scholars decode which ancient script?",
        templates=HISTORY_TEXT_TEMPLATES,
    ),
    _choice_seed(
        "history:silk-road-trade",
        "history",
        1,
        "history.silk-road-trade",
        subcategory="trade-networks",
        mode="classification",
        question="The Silk Road was mainly a network for what?",
        options=("long-distance trade", "submarine warfare", "printing newspapers"),
        answer="long-distance trade",
        templates=HISTORY_CHOICE_TEMPLATES,
    ),
    _text_seed(
        "history:meiji-japan",
        "history",
        2,
        "history.meiji-restoration",
        subcategory="state-modernization",
        mode="context",
        accepted=("japan",),
        clue="The Meiji Restoration transformed which country in the late 1800s?",
        templates=HISTORY_TEXT_TEMPLATES,
    ),
    _choice_seed(
        "history:magna-carta-power",
        "history",
        2,
        "history.magna-carta",
        subcategory="law-and-rights",
        mode="significance",
        question="Why is Magna Carta often remembered?",
        options=("it limited royal power", "it invented paper money", "it ended the Cold War"),
        answer="it limited royal power",
        templates=HISTORY_CHOICE_TEMPLATES,
    ),
    _text_seed(
        "history:trench-warfare-wwi",
        "history",
        2,
        "history.world-war-one-trenches",
        subcategory="warfare",
        mode="association",
        accepted=("world war i", "wwi", "first world war"),
        clue="Trench warfare is most strongly associated with which war?",
        templates=HISTORY_TEXT_TEMPLATES,
    ),
    _text_seed(
        "history:marshall-plan-europe",
        "history",
        2,
        "history.marshall-plan",
        subcategory="postwar-reconstruction",
        mode="context",
        accepted=("europe",),
        clue="The Marshall Plan sent aid to rebuild which region after World War II?",
        templates=HISTORY_TEXT_TEMPLATES,
    ),
    _text_seed(
        "history:house-of-wisdom-baghdad",
        "history",
        3,
        "history.house-of-wisdom",
        subcategory="knowledge-centers",
        mode="context",
        accepted=("baghdad",),
        clue="The Abbasid House of Wisdom was centered in which city?",
        templates=HISTORY_TEXT_TEMPLATES,
    ),
    _text_seed(
        "history:zheng-he-ming",
        "history",
        3,
        "history.zheng-he-voyages",
        subcategory="maritime-history",
        mode="context",
        accepted=("ming", "ming dynasty"),
        clue="Admiral Zheng He sailed under which Chinese dynasty?",
        templates=HISTORY_TEXT_TEMPLATES,
    ),
    _choice_seed(
        "history:berlin-airlift-supply",
        "history",
        2,
        "history.berlin-airlift",
        subcategory="cold-war",
        mode="cause-effect",
        question="The Berlin Airlift was organized to do what?",
        options=("supply West Berlin by air", "evacuate Paris", "invade Japan"),
        answer="supply West Berlin by air",
        templates=HISTORY_CHOICE_TEMPLATES,
    ),
    _text_seed(
        "history:seneca-falls-suffrage",
        "history",
        2,
        "history.suffrage-movement",
        subcategory="social-movements",
        mode="goal",
        accepted=("womens suffrage", "women's suffrage", "suffrage"),
        clue="The Seneca Falls Convention is most associated with the push for what expanding right?",
        templates=HISTORY_TEXT_TEMPLATES,
    ),
    _ordered_seed(
        "history:order-print-steam-telegraph",
        "history",
        3,
        "history.technology-timeline",
        subcategory="chronology",
        mode="ordering",
        question="Arrange these inventions from earliest to latest",
        tokens=("printing press", "steam engine", "telegraph"),
        templates=HISTORY_ORDERED_TEMPLATES,
    ),
    _ordered_seed(
        "history:order-feudalism-renaissance-enlightenment",
        "history",
        3,
        "history.intellectual-movements-timeline",
        subcategory="chronology",
        mode="ordering",
        question="Arrange these eras and movements from earliest to latest",
        tokens=("feudalism", "renaissance", "enlightenment"),
        templates=HISTORY_ORDERED_TEMPLATES,
    ),
    _text_seed(
        "history:ghana-independence",
        "history",
        3,
        "history.decolonization-ghana",
        subcategory="decolonization",
        mode="milestone",
        accepted=("ghana",),
        clue="In 1957, which country became the first sub-Saharan African colony to gain independence in the postwar wave?",
        templates=HISTORY_TEXT_TEMPLATES,
    ),
    _text_seed(
        "history:navajo-code-talkers",
        "history",
        3,
        "history.code-talkers-navajo",
        subcategory="warfare",
        mode="context",
        accepted=("navajo", "navajo language", "the navajo language"),
        clue="In the Pacific theater of World War II, U.S. forces famously used speakers of which language as code talkers?",
        templates=HISTORY_TEXT_TEMPLATES,
    ),
    _choice_seed(
        "history:glasnost-openness",
        "history",
        3,
        "history.soviet-reform-glasnost",
        subcategory="cold-war",
        mode="definition",
        question="In late Soviet politics, glasnost called for more of what?",
        options=("openness", "collectivized farming", "royal succession"),
        answer="openness",
        templates=HISTORY_CHOICE_TEMPLATES,
    ),
    _text_seed(
        "history:toussaint-louverture",
        "history",
        3,
        "history.haitian-revolution",
        subcategory="revolutions",
        mode="identity",
        accepted=("toussaint louverture", "louverture"),
        clue="Which revolutionary leader became the central figure of the Haitian Revolution?",
        templates=HISTORY_TEXT_TEMPLATES,
    ),
    _choice_seed(
        "history:vienna-congress-balance-power",
        "history",
        3,
        "history.congress-of-vienna",
        subcategory="diplomacy",
        mode="goal",
        question="After Napoleon's defeat, the Congress of Vienna mainly tried to restore what across Europe?",
        options=("a balance of power", "feudal serfdom everywhere", "Greek democracy"),
        answer="a balance of power",
        templates=HISTORY_CHOICE_TEMPLATES,
    ),
    _text_seed(
        "geography:danube-river",
        "geography",
        2,
        "geography.rivers-danube",
        subcategory="rivers",
        mode="identity",
        accepted=("danube", "the danube"),
        clue="Which river links Vienna, Budapest, and Belgrade?",
        templates=GEOGRAPHY_TEXT_TEMPLATES,
    ),
    _text_seed(
        "geography:norway-fjords",
        "geography",
        1,
        "geography.landforms-fjords",
        subcategory="landforms",
        mode="identity",
        accepted=("norway",),
        clue="Fjords are especially associated with which country?",
        templates=GEOGRAPHY_TEXT_TEMPLATES,
    ),
    _choice_seed(
        "geography:monsoon-definition",
        "geography",
        2,
        "geography.climate-monsoon",
        subcategory="climate",
        mode="definition",
        question="A monsoon is best described as what?",
        options=("a seasonal wind reversal", "a chain of volcanoes", "a deep ocean trench"),
        answer="a seasonal wind reversal",
        templates=GEOGRAPHY_CHOICE_TEMPLATES,
    ),
    _text_seed(
        "geography:rain-shadow",
        "geography",
        3,
        "geography.climate-rain-shadow",
        subcategory="climate",
        mode="causal",
        accepted=("rain shadow", "a rain shadow"),
        clue="The dry side of a mountain range created after moist air drops rain is called a what?",
        templates=GEOGRAPHY_TEXT_TEMPLATES,
    ),
    _choice_seed(
        "geography:red-sea-location",
        "geography",
        2,
        "geography.seas-red-sea",
        subcategory="waterways",
        mode="spatial",
        question="Which body of water lies between northeast Africa and the Arabian Peninsula?",
        options=("Red Sea", "Baltic Sea", "Caribbean Sea"),
        answer="Red Sea",
        templates=GEOGRAPHY_CHOICE_TEMPLATES,
    ),
    _text_seed(
        "geography:mekong-region",
        "geography",
        2,
        "geography.rivers-mekong",
        subcategory="rivers",
        mode="region",
        accepted=("southeast asia",),
        clue="The Mekong is most associated with which world region?",
        templates=GEOGRAPHY_TEXT_TEMPLATES,
    ),
    _text_seed(
        "geography:tibetan-plateau",
        "geography",
        3,
        "geography.plateaus-tibetan",
        subcategory="landforms",
        mode="identity",
        accepted=("tibetan plateau", "the tibetan plateau"),
        clue="Which plateau is nicknamed the Roof of the World?",
        templates=GEOGRAPHY_TEXT_TEMPLATES,
    ),
    _text_seed(
        "geography:andes-west-coast",
        "geography",
        2,
        "geography.mountains-andes",
        subcategory="mountains",
        mode="spatial",
        accepted=("west", "the west coast", "west coast", "western side"),
        clue="The Andes run along which side of South America?",
        templates=GEOGRAPHY_TEXT_TEMPLATES,
    ),
    _text_seed(
        "geography:suez-red-sea",
        "geography",
        2,
        "geography.canals-suez",
        subcategory="waterways",
        mode="connection",
        accepted=("red sea", "the red sea"),
        clue="The Suez Canal links the Mediterranean Sea with which sea?",
        templates=GEOGRAPHY_TEXT_TEMPLATES,
    ),
    _text_seed(
        "geography:sahel-africa",
        "geography",
        2,
        "geography.regions-sahel",
        subcategory="regions",
        mode="region",
        accepted=("africa",),
        clue="The Sahel lies between the Sahara and wetter savannas on which continent?",
        templates=GEOGRAPHY_TEXT_TEMPLATES,
    ),
    _choice_seed(
        "geography:amazon-climate",
        "geography",
        2,
        "geography.climate-amazon",
        subcategory="climate",
        mode="classification",
        question="Most of the Amazon Basin has which broad climate?",
        options=("tropical rainforest", "tundra", "Mediterranean"),
        answer="tropical rainforest",
        templates=GEOGRAPHY_CHOICE_TEMPLATES,
    ),
    _ordered_seed(
        "geography:order-reykjavik-london-athens",
        "geography",
        3,
        "geography.latitude-order",
        subcategory="relative-position",
        mode="ordering",
        question="Arrange these cities from north to south",
        tokens=("reykjavik", "london", "athens"),
        templates=GEOGRAPHY_ORDERED_TEMPLATES,
    ),
    _choice_seed(
        "geography:bolivia-landlocked",
        "geography",
        1,
        "geography.country-traits-landlocked",
        subcategory="country-traits",
        mode="classification",
        question="Which country is landlocked?",
        options=("Bolivia", "Portugal", "Japan"),
        answer="Bolivia",
        templates=GEOGRAPHY_CHOICE_TEMPLATES,
    ),
    _text_seed(
        "geography:strait-of-malacca",
        "geography",
        3,
        "geography.waterways-strait-of-malacca",
        subcategory="waterways",
        mode="identity",
        accepted=("strait of malacca", "the strait of malacca"),
        clue="Which narrow strait between the Malay Peninsula and Sumatra is one of the world's busiest shipping lanes?",
        templates=GEOGRAPHY_TEXT_TEMPLATES,
    ),
    _choice_seed(
        "geography:delta-definition",
        "geography",
        2,
        "geography.river-deltas",
        subcategory="landforms",
        mode="definition",
        question="A river delta forms where a river does what?",
        options=("deposits sediment near its mouth", "cuts a canyon through dry rock", "circles a volcano"),
        answer="deposits sediment near its mouth",
        templates=GEOGRAPHY_CHOICE_TEMPLATES,
    ),
    _text_seed(
        "geography:great-dividing-range-australia",
        "geography",
        2,
        "geography.mountains-great-dividing-range",
        subcategory="mountains",
        mode="location",
        accepted=("australia",),
        clue="The Great Dividing Range runs along the eastern side of which country?",
        templates=GEOGRAPHY_TEXT_TEMPLATES,
    ),
    _ordered_seed(
        "geography:order-buenos-aires-lima-bogota",
        "geography",
        3,
        "geography.latitude-order-south-america",
        subcategory="relative-position",
        mode="ordering",
        question="Arrange these South American capitals from south to north",
        tokens=("buenos aires", "lima", "bogota"),
        templates=GEOGRAPHY_ORDERED_TEMPLATES,
    ),
    _text_seed(
        "language:suffix-less",
        "language",
        1,
        "language.word-parts-less",
        subcategory="word-parts",
        mode="definition",
        accepted=("without",),
        clue="The suffix -less usually means what?",
        templates=LANGUAGE_TEXT_TEMPLATES,
    ),
    _text_seed(
        "language:break-the-ice",
        "language",
        2,
        "language.idioms-break-the-ice",
        subcategory="idioms",
        mode="meaning",
        accepted=("start conversation", "ease tension", "make people comfortable"),
        clue="If someone says a joke to break the ice, what are they trying to do?",
        templates=LANGUAGE_TEXT_TEMPLATES,
    ),
    _choice_seed(
        "language:onomatopoeia-buzz",
        "language",
        2,
        "language.sound-words",
        subcategory="word-classes",
        mode="classification",
        question="Which word is onomatopoeic?",
        options=("buzz", "idea", "calm"),
        answer="buzz",
        templates=LANGUAGE_CHOICE_TEMPLATES,
    ),
    _text_seed(
        "language:chrono-time",
        "language",
        2,
        "language.roots-chrono",
        subcategory="roots",
        mode="definition",
        accepted=("time",),
        clue="The root chrono- relates to what?",
        templates=LANGUAGE_TEXT_TEMPLATES,
    ),
    _boolean_seed(
        "language:semicolon-clauses",
        "language",
        2,
        "language.punctuation-semicolon",
        subcategory="grammar",
        mode="principle",
        statement="A semicolon can join two closely related independent clauses.",
        value=True,
        templates=LANGUAGE_BOOLEAN_TEMPLATES,
        extra_tags=("sub:punctuation-semicolon",),
    ),
    _text_seed(
        "language:scarce-antonym",
        "language",
        1,
        "language.antonyms-scarce",
        subcategory="meaning",
        mode="contrast",
        accepted=("abundant", "plentiful"),
        clue="What is the opposite of scarce?",
        templates=LANGUAGE_TEXT_TEMPLATES,
    ),
    _ordered_seed(
        "language:brunch-portmanteau",
        "language",
        2,
        "language.portmanteau-brunch",
        subcategory="word-formation",
        mode="ordering",
        question="Arrange the two source meals in the order the blended word begins and ends with them",
        tokens=("breakfast", "lunch"),
        templates=LANGUAGE_ORDERED_TEMPLATES,
    ),
    _choice_seed(
        "language:parallel-structure",
        "language",
        3,
        "language.parallelism",
        subcategory="usage",
        mode="editing",
        question="Which sentence keeps parallel structure?",
        options=(
            "She likes hiking, painting, and to sing.",
            "She likes hiking, painting, and singing.",
            "She likes hike, painting, and singer.",
        ),
        answer="She likes hiking, painting, and singing.",
        templates=LANGUAGE_CHOICE_TEMPLATES,
        extra_tags=("sub:parallelism",),
    ),
    _choice_seed(
        "language:formal-email",
        "language",
        2,
        "language.register-formality",
        subcategory="register",
        mode="usage",
        question="Which phrase sounds most formal in an email?",
        options=("Hey, got your note", "I received your message", "Yo, saw this"),
        answer="I received your message",
        templates=LANGUAGE_CHOICE_TEMPLATES,
    ),
    _text_seed(
        "language:figurative-zoo",
        "language",
        2,
        "language.figurative-zoo",
        subcategory="figurative-language",
        mode="classification",
        accepted=("figurative", "figuratively"),
        clue="In the sentence 'the classroom was a zoo,' is zoo being used literally or figuratively?",
        templates=LANGUAGE_TEXT_TEMPLATES,
    ),
    _choice_seed(
        "language:malapropism-definition",
        "language",
        3,
        "language.malapropism",
        subcategory="usage",
        mode="definition",
        question="A malapropism is best described as what?",
        options=(
            "using a similar-sounding wrong word",
            "repeating a consonant sound",
            "making up a fantasy world",
        ),
        answer="using a similar-sounding wrong word",
        templates=LANGUAGE_CHOICE_TEMPLATES,
        extra_tags=("sub:malapropism",),
    ),
    _choice_seed(
        "language:affect-verb-choice",
        "language",
        3,
        "language.affect-effect-usage",
        subcategory="usage",
        mode="editing",
        question="Which sentence uses affect as a verb meaning influence?",
        options=(
            "The weather can affect the turnout.",
            "The weather had a calm affect.",
            "The turnout was an affect of rain.",
        ),
        answer="The weather can affect the turnout.",
        templates=LANGUAGE_CHOICE_TEMPLATES,
    ),
    _choice_seed(
        "language:who-whom-object",
        "language",
        3,
        "language.who-whom-usage",
        subcategory="usage",
        mode="editing",
        question="Which sentence uses whom correctly?",
        options=(
            "Whom did the coach choose as captain?",
            "Who did you give the trophy to whom?",
            "Whom is leading the parade?",
        ),
        answer="Whom did the coach choose as captain?",
        templates=LANGUAGE_CHOICE_TEMPLATES,
    ),
    _choice_seed(
        "language:metaphor-example",
        "language",
        2,
        "language.metaphor-identification",
        subcategory="figurative-language",
        mode="classification",
        question="Which sentence uses a metaphor rather than a simile or a literal statement?",
        options=(
            "The deadline was a brick wall.",
            "The deadline felt like a brick wall.",
            "The deadline arrived at noon.",
        ),
        answer="The deadline was a brick wall.",
        templates=LANGUAGE_CHOICE_TEMPLATES,
    ),
    _text_seed(
        "language:root-bene",
        "language",
        2,
        "language.roots-bene",
        subcategory="roots",
        mode="definition",
        accepted=("good", "well"),
        clue="The root bene- points to what general idea?",
        templates=LANGUAGE_TEXT_TEMPLATES,
    ),
    _text_seed(
        "language:oxymoron-definition",
        "language",
        3,
        "language.oxymoron-definition",
        subcategory="figurative-language",
        mode="definition",
        accepted=("oxymoron", "an oxymoron"),
        clue="When a phrase pairs opposite ideas like 'deafening silence,' what figure of speech is it called?",
        templates=LANGUAGE_TEXT_TEMPLATES,
    ),
    _choice_seed(
        "language:semicolon-fix",
        "language",
        3,
        "language.comma-splice-revision",
        subcategory="punctuation",
        mode="editing",
        question="Which revision correctly fixes the comma splice?",
        options=(
            "The storm passed, we went outside.",
            "The storm passed; then we went outside.",
            "The storm passed because we went outside.",
        ),
        answer="The storm passed; then we went outside.",
        templates=LANGUAGE_CHOICE_TEMPLATES,
    ),
    _text_seed(
        "logic:middle-seat",
        "logic",
        1,
        "logic.order-middle-seat",
        subcategory="ordering",
        mode="deduction",
        accepted=("cora",),
        clue="Ava sits left of Ben. Cora sits between them. Who sits in the middle?",
        templates=LOGIC_TEXT_TEMPLATES,
    ),
    _choice_seed(
        "logic:prize-box-blue",
        "logic",
        3,
        "logic.exactly-one-true-boxes",
        subcategory="truth-rules",
        mode="deduction",
        question=(
            "Exactly one label is true. Red says 'The prize is in blue.' "
            "Blue says 'The prize is not here.' Green says 'The prize is in red.' Where is the prize?"
        ),
        options=("red", "blue", "green"),
        answer="blue",
        templates=LOGIC_CHOICE_TEMPLATES,
    ),
    _boolean_seed(
        "logic:all-some-rust",
        "logic",
        2,
        "logic.quantifiers-rust",
        subcategory="quantifiers",
        mode="inference",
        statement="All lanterns are metal and some metal things rust. That proves some lanterns rust.",
        value=False,
        templates=LOGIC_BOOLEAN_TEMPLATES,
    ),
    _text_seed(
        "logic:finish-last",
        "logic",
        1,
        "logic.rank-last",
        subcategory="ordering",
        mode="deduction",
        accepted=("paz",),
        clue="Mika finishes before Noor. Noor finishes before Paz. Who finishes last?",
        templates=LOGIC_TEXT_TEMPLATES,
    ),
    _choice_seed(
        "logic:doubling-pattern",
        "logic",
        2,
        "logic.pattern-doubling",
        subcategory="patterns",
        mode="analogy",
        question="Which list follows the same doubling pattern as 2, 4, 8, 16?",
        options=("3, 6, 12, 24", "5, 10, 15, 20", "7, 9, 11, 13"),
        answer="3, 6, 12, 24",
        templates=LOGIC_CHOICE_TEMPLATES,
    ),
    _numeric_seed(
        "logic:code-947",
        "logic",
        3,
        "logic.code-ordering",
        subcategory="code-breaking",
        mode="deduction",
        question="A three-digit code uses 4, 7, and 9 once each. The 4 is before 7, 9 is not last, and the code is greater than 700. What code fits?",
        value=947,
        templates=LOGIC_NUMERIC_TEMPLATES,
    ),
    _boolean_seed(
        "logic:east-west-return",
        "logic",
        1,
        "logic.spatial-return",
        subcategory="spatial",
        mode="verification",
        statement="If you move one step east and then one step west, you end west of where you started.",
        value=False,
        templates=LOGIC_BOOLEAN_TEMPLATES,
    ),
    _ordered_seed(
        "logic:book-order-left-right",
        "logic",
        2,
        "logic.relative-position-books",
        subcategory="ordering",
        mode="deduction",
        question="Arrange the books from left to right using the clues: the G book is to the right of the B book, and the B book is to the right of the R book",
        tokens=("red", "blue", "green"),
        templates=LOGIC_ORDERED_TEMPLATES,
    ),
    _choice_seed(
        "logic:bird-owner-paz",
        "logic",
        2,
        "logic.assignment-pets",
        subcategory="assignment",
        mode="elimination",
        question=(
            "Nia, Omar, and Paz each chose one pet: cat, dog, or bird. "
            "Nia did not choose cat. Paz chose neither cat nor dog. Who chose bird?"
        ),
        options=("Nia", "Omar", "Paz"),
        answer="Paz",
        templates=LOGIC_CHOICE_TEMPLATES,
    ),
    _choice_seed(
        "logic:exactly-one-true-key",
        "logic",
        3,
        "logic.exactly-one-true-key",
        subcategory="truth-rules",
        mode="deduction",
        question=(
            "Exactly one statement is true. Ivo says 'The key is silver.' "
            "June says 'The key is brass.' Kai says 'Ivo is telling the truth.' What color is the key?"
        ),
        options=("silver", "brass", "copper"),
        answer="brass",
        templates=LOGIC_CHOICE_TEMPLATES,
    ),
    _choice_seed(
        "logic:right-turn-cycle",
        "logic",
        1,
        "logic.rotation-cycle",
        subcategory="rotation",
        mode="pattern",
        question="A robot keeps turning right: north, east, south, west. Which direction comes next?",
        options=("north", "south", "west"),
        answer="north",
        templates=LOGIC_CHOICE_TEMPLATES,
    ),
    _boolean_seed(
        "logic:not-icy-not-comet",
        "logic",
        2,
        "logic.contrapositive-comet",
        subcategory="inference",
        mode="logic-rule",
        statement="If every comet is icy and Nova is not icy, that proves Nova is not a comet.",
        value=True,
        templates=LOGIC_BOOLEAN_TEMPLATES,
        extra_tags=("sub:contrapositive-comet",),
    ),
    _choice_seed(
        "logic:mango-owner-cora",
        "logic",
        2,
        "logic.assignment-fruit",
        subcategory="assignment",
        mode="elimination",
        question=(
            "Ava, Ben, and Cora each chose one fruit: apple, pear, or mango. "
            "Ava did not choose apple. Ben did not choose mango. Cora chose neither apple nor pear. Who chose mango?"
        ),
        options=("Ava", "Ben", "Cora"),
        answer="Cora",
        templates=LOGIC_CHOICE_TEMPLATES,
    ),
    _ordered_seed(
        "logic:performer-lineup-left-right",
        "logic",
        2,
        "logic.relative-position-performers",
        subcategory="ordering",
        mode="deduction",
        question="Arrange the performers from left to right using the clues: C stands to the right of B, and B stands to the right of A",
        tokens=("Aya", "Bianca", "Cora"),
        templates=LOGIC_ORDERED_TEMPLATES,
    ),
    _text_seed(
        "logic:least-score-sol",
        "logic",
        1,
        "logic.rank-least-score",
        subcategory="ordering",
        mode="deduction",
        accepted=("sol",),
        clue="Lina scored more than Mara, and Mara scored more than Sol. Who scored the least?",
        templates=LOGIC_TEXT_TEMPLATES,
    ),
    _text_seed(
        "logic:between-day-order",
        "logic",
        2,
        "logic.sequence-between",
        subcategory="ordering",
        mode="deduction",
        accepted=("tuesday",),
        clue="If the meeting is after Monday and before Wednesday, which day fits?",
        templates=LOGIC_TEXT_TEMPLATES,
    ),
    _numeric_seed(
        "math:quarter-of-eighty",
        "math",
        1,
        "math.benchmarks-quarter",
        subcategory="benchmarks",
        mode="number-sense",
        question="Twenty-five percent of 80 is the same as one quarter of 80. What is it?",
        value=20,
        templates=MATH_NUMERIC_TEMPLATES,
    ),
    _choice_seed(
        "math:closest-to-half",
        "math",
        2,
        "math.fraction-benchmarks",
        subcategory="fractions",
        mode="comparison",
        question="Which value is closest to one half?",
        options=("49/100", "3/5", "7/16"),
        answer="49/100",
        templates=MATH_CHOICE_TEMPLATES,
    ),
    _numeric_seed(
        "math:ninety-nine-times-twelve",
        "math",
        2,
        "math.compensation-ninety-nine",
        subcategory="mental-multiplication",
        mode="compensation",
        question="Use a quick compensation trick: 99 x 12 is 100 x 12 minus 12. What is the product?",
        value=1188,
        templates=MATH_NUMERIC_TEMPLATES,
    ),
    _numeric_seed(
        "math:square-between-thirty-forty",
        "math",
        1,
        "math.square-recognition",
        subcategory="number-properties",
        mode="recognition",
        question="Which perfect square lies between 30 and 40?",
        value=36,
        templates=MATH_NUMERIC_TEMPLATES,
    ),
    _numeric_seed(
        "math:recipe-scale-broth",
        "math",
        2,
        "math.ratio-recipe-scale",
        subcategory="ratios",
        mode="proportional-reasoning",
        question="A recipe for 4 uses 6 cups of broth. At the same ratio, how many cups are needed for 6 servings?",
        value=9,
        templates=MATH_NUMERIC_TEMPLATES,
    ),
    _numeric_seed(
        "math:digit-divisible-by-nine",
        "math",
        2,
        "math.divisibility-missing-digit",
        subcategory="divisibility",
        mode="number-sense",
        question="What digit makes 531 divisible by 9 after replacing the final 1 with that digit in 53_?",
        value=1,
        templates=MATH_NUMERIC_TEMPLATES,
    ),
    _numeric_seed(
        "math:balanced-average",
        "math",
        2,
        "math.average-balance",
        subcategory="averages",
        mode="reasoning",
        question="A class average is 72. One score is 8 points above average and another is 8 below. What is the average of those two scores together?",
        value=72,
        templates=MATH_NUMERIC_TEMPLATES,
    ),
    _numeric_seed(
        "math:double-half-product",
        "math",
        2,
        "math.double-and-half",
        subcategory="mental-multiplication",
        mode="transformation",
        question="15 x 16 has the same product as 30 x 8. What is the product?",
        value=240,
        templates=MATH_NUMERIC_TEMPLATES,
    ),
    _numeric_seed(
        "math:clock-angle-three",
        "math",
        1,
        "math.clock-angles",
        subcategory="geometry",
        mode="recognition",
        question="At exactly 3:00, what angle do the clock hands make?",
        value=90,
        templates=MATH_NUMERIC_TEMPLATES,
    ),
    _numeric_seed(
        "math:remainder-fifty-three-by-five",
        "math",
        1,
        "math.remainder-short",
        subcategory="remainders",
        mode="number-sense",
        question="What remainder does 53 leave when divided by 5?",
        value=3,
        templates=MATH_NUMERIC_TEMPLATES,
    ),
    _choice_seed(
        "math:ratio-equals-three-fourths",
        "math",
        2,
        "math.ratio-equivalence",
        subcategory="ratios",
        mode="comparison",
        question="Which ratio is equivalent to 3:4?",
        options=("9:12", "12:15", "15:18"),
        answer="9:12",
        templates=MATH_CHOICE_TEMPLATES,
    ),
    _numeric_seed(
        "math:consecutive-sum-twenty-five",
        "math",
        3,
        "math.consecutive-integers",
        subcategory="algebra-lite",
        mode="reasoning",
        question="Two consecutive integers add to 25. What is the larger integer?",
        value=13,
        templates=MATH_NUMERIC_TEMPLATES,
    ),
    _numeric_seed(
        "math:difference-of-squares-19-21",
        "math",
        3,
        "math.difference-of-squares",
        subcategory="algebra-lite",
        mode="transformation",
        question="Use a difference-of-squares shortcut: what is 21^2 - 19^2?",
        value=80,
        templates=MATH_NUMERIC_TEMPLATES,
    ),
    _numeric_seed(
        "math:average-five-round-finish",
        "math",
        3,
        "math.average-target-score",
        subcategory="averages",
        mode="reasoning",
        question="After 4 rounds, a player's scores total 52. What score in round 5 gives an average of 14 across all 5 rounds?",
        value=18,
        templates=MATH_NUMERIC_TEMPLATES,
    ),
    _text_seed(
        "culture:foley-sound-effects",
        "culture",
        2,
        "culture.film-foley",
        subcategory="film",
        mode="function",
        accepted=("sound effects", "sound effect", "effects sounds"),
        clue="In film, foley artists mainly create what?",
        templates=CULTURE_TEXT_TEMPLATES,
    ),
    _choice_seed(
        "culture:checkmate-description",
        "culture",
        1,
        "culture.games-checkmate",
        subcategory="games",
        mode="definition",
        question="Which statement describes checkmate in chess?",
        options=(
            "the king is in check and cannot escape",
            "a pawn reaches the last rank",
            "both players repeat positions",
        ),
        answer="the king is in check and cannot escape",
        templates=CULTURE_CHOICE_TEMPLATES,
    ),
    _numeric_seed(
        "culture:sonnet-lines",
        "culture",
        2,
        "culture.poetry-sonnet",
        subcategory="literature",
        mode="fact",
        question="How many lines are in a traditional sonnet?",
        value=14,
        templates=CULTURE_NUMERIC_TEMPLATES,
    ),
    _text_seed(
        "culture:improv-yes-and",
        "culture",
        2,
        "culture.improv-yes-and",
        subcategory="performance",
        mode="phrase",
        accepted=("yes and", "yes, and"),
        clue="What phrase captures the classic improv rule of accepting an idea and building on it?",
        templates=CULTURE_TEXT_TEMPLATES,
    ),
    _numeric_seed(
        "culture:haiku-syllables",
        "culture",
        2,
        "culture.poetry-haiku",
        subcategory="literature",
        mode="fact",
        question="How many syllables are in the traditional 5-7-5 haiku pattern?",
        value=17,
        templates=CULTURE_NUMERIC_TEMPLATES,
    ),
    _text_seed(
        "culture:lp-speed",
        "culture",
        3,
        "culture.music-vinyl-speed",
        subcategory="music",
        mode="fact",
        accepted=("33 1/3 rpm", "33 1/3", "33 1 3 rpm"),
        clue="A standard LP record usually spins at what speed?",
        templates=CULTURE_TEXT_TEMPLATES,
    ),
    _text_seed(
        "culture:ensemble-cast",
        "culture",
        2,
        "culture.storytelling-ensemble",
        subcategory="storytelling",
        mode="definition",
        accepted=("ensemble", "ensemble cast"),
        clue="A story focused on several major characters rather than one lead is often called an what cast?",
        templates=CULTURE_TEXT_TEMPLATES,
    ),
    _choice_seed(
        "culture:biopic-definition",
        "culture",
        1,
        "culture.film-biopic",
        subcategory="film",
        mode="classification",
        question="A film dramatizing a real person's life is usually called what?",
        options=("biopic", "mockumentary", "anthology"),
        answer="biopic",
        templates=CULTURE_CHOICE_TEMPLATES,
    ),
    _text_seed(
        "culture:metronome-tempo",
        "culture",
        1,
        "culture.music-metronome",
        subcategory="music",
        mode="function",
        accepted=("tempo", "time"),
        clue="A metronome helps musicians keep what?",
        templates=CULTURE_TEXT_TEMPLATES,
    ),
    _text_seed(
        "culture:comics-gutter",
        "culture",
        2,
        "culture.comics-gutter",
        subcategory="comics",
        mode="definition",
        accepted=("gutter", "the gutter"),
        clue="In comics, the space between panels is called the what?",
        templates=CULTURE_TEXT_TEMPLATES,
    ),
    _choice_seed(
        "culture:grand-slam-tennis",
        "culture",
        2,
        "culture.sports-grand-slam",
        subcategory="sports",
        mode="definition",
        question="In tennis, winning all four major tournaments in one year is called what?",
        options=("a Grand Slam", "a hat trick", "a clean sheet"),
        answer="a Grand Slam",
        templates=CULTURE_CHOICE_TEMPLATES,
    ),
    _text_seed(
        "culture:storyboard-purpose",
        "culture",
        2,
        "culture.film-storyboard",
        subcategory="film",
        mode="function",
        accepted=("plan shots", "plan scenes", "visual planning"),
        clue="What is the main purpose of a storyboard in film or animation production?",
        templates=CULTURE_TEXT_TEMPLATES,
    ),
    _ordered_seed(
        "culture:solo-duet-quartet",
        "culture",
        1,
        "culture.music-ensemble-order",
        subcategory="music",
        mode="ordering",
        question="Arrange these ensemble terms from smallest group to largest group",
        tokens=("solo", "duet", "quartet"),
        templates=CULTURE_ORDERED_TEMPLATES,
    ),
    _choice_seed(
        "culture:staccato-description",
        "culture",
        2,
        "culture.music-staccato",
        subcategory="music",
        mode="definition",
        question="In music, staccato tells you to play notes how?",
        options=("short and detached", "smoothly connected", "gradually slower"),
        answer="short and detached",
        templates=CULTURE_CHOICE_TEMPLATES,
    ),
    _text_seed(
        "culture:matinee-definition",
        "culture",
        1,
        "culture.performance-matinee",
        subcategory="performance",
        mode="definition",
        accepted=("matinee", "a matinee"),
        clue="What do you call a theater or movie performance scheduled in the afternoon?",
        templates=CULTURE_TEXT_TEMPLATES,
    ),
    _choice_seed(
        "culture:cliffhanger-definition",
        "culture",
        2,
        "culture.storytelling-cliffhanger",
        subcategory="storytelling",
        mode="definition",
        question="A cliffhanger ending usually does what?",
        options=(
            "leaves a major outcome unresolved",
            "summarizes every subplot neatly",
            "switches the story to documentary footage",
        ),
        answer="leaves a major outcome unresolved",
        templates=CULTURE_CHOICE_TEMPLATES,
    ),
    _text_seed(
        "culture:montage-purpose",
        "culture",
        2,
        "culture.film-montage",
        subcategory="film",
        mode="function",
        accepted=("passage of time", "show passage of time", "compress time", "condense time"),
        clue="In film editing, a montage often helps show what efficiently across a short sequence?",
        templates=CULTURE_TEXT_TEMPLATES,
    ),
)
